const lyrics = [
  [
    '[Intro: Kendrick Lamar]',
    'I got a story to tell, you know that I cherish thee',
    "Hope it ain't too many feelings involved",

    '[Refrain: Lil Wayne]',
    'I see niggas in this bitch stunting, popping bottles',
    'Getting drunk with these bitches',
    'Then when they leave, they get followed',
    'Fall asleep with that bitch',
    "And really don't know much about her",
    'Then she let us in, we take all of your shit',
    'And when you wake up, she help you try to find it, I love her',

    '[Verse 1: Lil Wayne]',
    'I be with bitches that be with bitches',
    'That be with niggas with riches',
    "I tell her, 'Get him,' she say, 'I got you'",
    "I say, 'No, bitch, I said get him' (Ha)",
    'And they so pretty, and they hair lengthy',
    'He hit it and sleep on her titties',
    'Then she give us the word, we come through with AKs',
    "It's a stick-up, she scream like a victim, now you",
    'Feeling so silly, I smoke color purple',
    "I'm up in here feeling like Celie, ooh",
    "Nappy-ass dreads, what's that you say?",
    'Watch your mouth, Milli Vanilli, ooh',
    'You can get snaked, you can get faked',
    "Out by the bitch that you feeling 'cause you",
    "Thought that she was an angel, that bitch ain't no angel",
    'I treat her halo like a frisbee, and you',
    'Tell her your business, she tell me your business',
    'You tell that bitch what you feeling',
    'All of the beans you be spilling, to you',
    'She lie through her teeth; cavities, fillings',
    "She know where you hide it, tell me where it's hidden",
    'She know when you gone, tell me when to visit',
    'We break in your home and take the specifics',
    'And meanwhile, the bitch is on vacation with him',
    "So she don't get blamed, we don't snatch chains",
    "We find out addresses, and we don't leave messes",
    "You'll only know that it's gone when you checking",
    'Then your first thought is to start second guessing',
    "She say, 'What's wrong?' He say, 'Nothing, keep resting,'",
    "She say, 'What's missing?'—'How you know something missing?'",
    "He scratched his head, she say, 'Get back in bed,'",
    "Then she gave him some head, boy, you can't trust them bitches",
    "And then she say, 'Ooh'",

    '[Refrain: Lil Wayne]',
    'I see niggas in this bitch stunting, popping bottles',
    'Getting drunk with these bitches',
    'Then when they leave, they get followed',
    'I be with bitches that know the bitches',
    "That's with the niggas we following",
    'Get them on the line, stay two cars behind',
    "And tell them hoes, 'Don't be so obvious!'",
    "Mona Lisa, long hair, don't care",
    "She handle the business and don't ever tell",
    'She bite the bullet and cough up the shell',
    "She tell 'em, 'Ooh, daddy, let's go to your place,'",
    "And if he say yeah, then we meet 'em there",
    'She feed him lies with his silverware',
    "She don't want love, she just want her share, I",

    '[Verse 2: Lil Wayne]',
    'Know a bitch named Liz',
    "This nigga think she his 'cause she tell him that it is",
    'So, he tell her all his secrets, he tell her all his fears',
    'And then she tell me, and I be all ears',
    'Then I go and tell my people, and they already know it',
    'And then I call Liz, and she say he coming over',
    "I say, 'Good girl, just remember what I told you'",
    "She gave me a salute, I say, 'Girl, you're a soldier!'",
    'We waiting outside, watch him pull up',
    'Walk up to the door, and right before he knocked',
    'She open the door naked, she left it unlocked',
    "They started French kissing so he didn't see moi",
    'And then she let him in, they stopped on the couch',
    'Music up loud with his head in the clouds',
    'Turn that shit down, and I scared the piss out him',
    'Piss a nigga off, put the gun to his frown',
    "'Nigga, turn around, I ain't here to fuck around",
    "I ain't here to fuck around, caught you with your pants down",
    'You know what it is, put your fucking hands up!',
    "Liz, that's enough, you can put your hands down'",
    'Then he looked dead at her and he shook his head at her',
    'She a good actress, and you a dead actor',
    "You'll be dead after we get what we after",
    "If Liz call you daddy, she 'bout to be a bastard, oh",
    'I got way too many bitches that do anything for me, nigga',
    'But think for me, nigga',
    "Send her to you like she ain't for me, nigga",
    'I hope you alone like bankruptcy, nigga',
    'She pour you a drink, that drink on me, nigga',
    'She slip something in it, now faint for me, nigga',
    'Mona Lisa, I done painted the picture',
    'Mo-Mona Lisa, out the frame on these niggas',
    'Pussy got you out of character, nigga',
    'You fall for these hoes off your ladder, my nigga',
    "Take everything that you have 'til you don't even have",
    'An opinion, we have your attention',
    'And now you looking down a barrel though, nigga',
    'Now she looking for her pantyhose, nigga',
    'We just looking for the casserole, nigga',
    "But she gon' show us where you stash it though, nigga, Mona",

    '[Verse 3: Kendrick Lamar & Lil Wayne]',
    'Ah, every day she wake up with a different color makeup',
    "And a promise he gon' take her to the movie and the mall",
    'Chilling with the Laker, on the floor, fourth quarter',
    'Four minute on the clock, Black Mamba with the ball',
    "Paparazzi looking at 'em both, popping up and take a picture, uh",
    'Probably on an internet blog',
    "In a minute, he gon' be admitting that he love her",
    'On his mother, man, he want to meet her mother by tomorrow',
    '(Mona Lisa)',
    'Pussy good enough, it got him sinning in the walls',
    'And he digging in it like he living in it, make a new religion with it',
    "Man, a nigga 'bout to go against God",
    'Poetry in the pear trees',
    'Sweet tone like a hummingbird when she asked him',
    'Did he want to make love in a yellow taxi?',
    'Never gave two fucks, jumped in the backseat',
    'Woke up in the morning to The Great Gatsby',
    'Then he dogged it again like the bitch Lassie',
    "I'm a dog in the wind, I'm a pet laughing",
    "I'ma call up again like I did last week",
    "Make good with the friend, and I'm all jazzy",
    'Britney with the twin and the girl, Ashley',
    'Found out that I fucked, he was unhappy',
    'Bitch, I never let the bullshit get past me',
    "Better yet, I wanna break up, don't you ask me",
    "'Bout no motherfucking double standard, acting",
    "Fucking on another nigga, that's a negative alone",
    "But you sucked his dick? That's just nasty",
    'Matter fact, bitch, gimme your phone! (No!)',
    "You fucking with Wayne's!? (No!)",
    'Bitch, gimme your phone! (No! Let me, let me take this call real quick—like a lollipop)',
    'He on your fucking ringtone!? Is that the shit that you do!?',
    'Touching yourself, looking at Kendrick videos',
    'Jump on the internet, watching his interviews',
    "I don't know what the fuck lately gotten into you",
    'Tell me who love you, I bet I love harder',
    'Forgot all the shit that I did for your daughter?',
    'The Pampers, the Pedialyte and my momma',
    'Daycare after school and she never did charge ya',
    'You scandalous as fuck, and I hope you blow up',
    'You know what? I give up, let me go get my gun',
    "I got one in the chamber I'm planning on aiming",
    'Goddammit, you know that the damage is done',
    "Bitch, I'm emotional 'cause I'm in stress",
    "I'm not supposed to go through this, I guess",
    'So in conclusion',
    "Since you like rappers that's killing that pussy, I'm killing myself",

    '[Chorus: Lil Wayne]',
    "She say, 'Ooh, daddy, ooh,'",
    'Mona Lisa, Mona Lisa',
    'Ooh, fake smile (Ooh)',
    'Mona Lisa, Mona Lisa',
    "She say, 'Ooh,' dead emotion (Ooh)",
    'Mona Lisa, Mona Lisa',
    'Now he get the picture',
    'Mona Lisa, Mona Lisa, yeah',
  ],
  [
    '[Verse 1]',
    "I know that you're hiding something from me",
    "That's been close to your heart",
    "And I felt it creepin' up every day",
    'Baby, right from the start',
    "I know that look you give when we're fighting (Fighting)",
    "We're fighting (Fighting)",
    "'Cause I used to be the one who was lying (Lying)",
    'Oh, lying (Lying)',
    '',
    '[Chorus]',
    'Oh, is there someone else or not?',
    "'Cause I wanna keep you close",
    "I don't wanna lose my spot",
    "'Cause I need to know",
    "If you're hurting him, or you're hurting me",
    "If I ain't with you, I don't wanna be",
    'Is there someone else or not?',
    'Ooh, or not?',
    '',
    '[Verse 2]',
    "I don't deserve someone loyal to me",
    "Don't you think I see?",
    "And I don't want to be a prisoner to who I used to be",
    'I swear I changed my ways for the better, the better',
    "'Cause I wanna be with you forever, forever",
    '',
    '[Chorus]',
    'Oh, is there someone else or not?',
    "'Cause I wanna keep you close",
    "I don't wanna lose my spot",
    "'Cause I need to know",
    "If you're hurting him, or you're hurting me",
    "If I ain't with you, I don't wanna be",
    'Is there someone else or not?',
    'Ooh, or not?',
  ],
  [
    '[Verse 1]',
    'Go ahead and park after dark',
    "Fallen star, I'm your one call away",
    'Motel halls, neon walls',
    'When night falls, I am your escape',

    '[Pre-Chorus]',
    'When you lay alone, I ache',
    'Something I wanted to feel',

    '[Chorus]',
    "If you’ve been waitin' for fallin' in love",
    'Babe, you don’t have to wait on me',
    "'Cause I've been aimin' for Heaven above",
    "But an angel ain't what I need",

    '[Verse 2]',
    "Not anyone, you're the one",
    "More than fun, you're the sanctuary",
    "'Cause what you want is what I want",
    'Sincerity',

    '[Pre-Chorus]',
    'Souls that dream alone lie awake',
    'I’ll give you somethin’ so real',

    '[Chorus]',
    "If you've been waitin’ for fallin' in love",
    "Babe, you don't have to wait on me",
    "'Cause I’ve been aimin' for Heaven above",
    "But an angel ain't what I need",

    '[Bridge]',
    'Hold me oh so close',
    "'Cause you never know",
    'Just how long our lives will be',

    '[Chorus]',
    "If you've been waitin' for fallin' in love",
    "Babe, you don't have to wait on me",
    "'Cause I've been aimin' for Heaven above",
    "But an angel ain't what I need",
  ],
  [
    '[Verse 1]',
    'We found each other',
    'I helped you out of a broken place',
    'You gave me comfort',
    'But falling for you was my mistake',

    '[Pre-Chorus]',
    'I put you on top, I put you on top',
    'I claimed you so proud and openly',
    'And when times were rough, when times were rough',
    'I made sure I held you close to me',

    '[Chorus]',
    'So call out my name (Call out my name)',
    'Call out my name when I kiss you so gently',
    'I want you to stay (Want you to stay)',
    "I want you to stay even though you don't want me",
    "Girl, why can't you wait? (Why can't you wait, baby?)",
    "Girl, why can't you wait 'til I fall out of love?",
    "Won't you call out my name? (Call out my name)",
    "Girl, call out my name, and I'll be on my way and",
    "I'll be on my—",

    '[Verse 2]',
    "I said I didn't feel nothing, baby, but I lied",
    'I almost cut a piece of myself for your life',
    'Guess I was just another pit stop',
    "'Til you made up your mind",
    'You just wasted my time',

    '[Pre-Chorus]',
    'You were on top, I put you on top',
    'I claimed you so proud and openly, babe',
    'And when times were rough, when times were rough',
    'I made sure I held you close to me',

    '[Chorus]',
    'So call out my name (Call out my name, baby)',
    'So call out my name when I kiss you so gently (Ohh)',
    'I want you to stay (I want you to stay)',
    "I want you to stay even though you don't want me",
    "Girl, why can't you wait? (Girl, why can't you wait 'til I?)",
    "Girl, why can't you wait 'til I fall out of loving?",
    'Babe, call out my name (Say call out my name, baby)',
    "Girl call out my name and I'll be on my way",
    "And, I'll be on my—",

    '[Outro]',
    'On my way, on my way',
    'On my way, on my way, ooh',
    'On my way, on my way, on my way',
    'On my way, on my way, on my way',
    '(On my)',
  ],
  [
    '[Verse 1]',
    'Watch the sunrise along the coast',
    "As we're both getting old",
    "I can't describe what I'm feeling",
    "And all I know is we're going home",
    "So, please don't let me go",
    "Don't let me go",

    '[Chorus]',
    "And if it's right, I don't care how long it takes",
    "As long as I'm with you, I've got a smile on my face",
    "Save your tears, it'll be okay",
    "All I know is you're here with me",

    '[Post-Chorus]',
    'Ooh-ooh, oh, oh-oh',
    'Oh-oh-oh-oh-oh',

    '[Verse 2]',
    "Watch the sunrise as we're getting old, oh-oh",
    "I can't describe, oh-oh",
    'I wish I could live through every memory again',
    'Just one more time before we float off in the wind',
    'And all the time we spent waiting for the light to take us in',
    'Have been the greatest moments of my life',

    '[Chorus]',
    "I don't care how long it takes",
    "As long as I'm with you, I've got a smile on my face",
    "Save your tears, it'll be okay",
    "You're here with me",

    '[Post-Chorus]',
    'Ooh-ooh, oh, oh-oh',
    'Oh-oh-oh-oh-oh',

    '[Outro]',
    "I can't describe, oh-oh",
  ],
  [
    '[Intro]',
    'Ayy',

    '[Verse 1]',
    "I'm tryna put you in the worst mood, ah",
    'P1 cleaner than your church shoes, ah',
    'Milli point two just to hurt you, ah',
    "All red Lamb' just to tease you, ah",
    'None of these toys on lease too, ah',
    'Made your whole year in a week too, yah',
    'Main bitch outta your league too, ah',
    'Side bitch outta your league too, ah',

    '[Pre-Chorus]',
    'House so empty, need a centerpiece',
    'Twenty racks a table, cut from ebony',
    'Cut that ivory into skinny pieces',
    'Then she clean it with her face, man, I love my baby, ah',
    "You talkin' money, need a hearin' aid",
    "You talkin' 'bout me, I don't see the shade",
    'Switch up my style, I take any lane',
    'I switch up my cup, I kill any pain',

    '[Chorus]',
    '(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)',
    "Look what you've done",
    '(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)',
    "I'm a motherfuckin' starboy",
    '(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)',
    "Look what you've done",
    '(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)',
    "I'm a motherfuckin' starboy",

    '[Verse 2]',
    'Every day, a nigga try to test me, ah',
    'Every day, a nigga try to end me, ah',
    'Pull off in that Roadster SV, ah',
    "Pockets overweight, gettin' hefty, ah",
    "Comin' for the king, that's a far cry, I",
    'I come alive in the fall time, I',
    "The competition, I don't really listen",
    "I'm in the blue Mulsanne, bumpin' New Edition",

    '[Pre-Chorus]',
    'House so empty, need a centerpiece',
    'Twenty racks a table, cut from ebony',
    'Cut that ivory into skinny pieces',
    'Then she clean it with her face, man, I love my baby, ah',
    "You talkin' money, need a hearin' aid",
    "You talkin' 'bout me, I don't see the shade",
    'Switch up my style, I take any lane',
    'I switch up my cup, I kill any pain',

    '[Chorus]',
    '(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)',
    "Look what you've done",
    '(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)',
    "I'm a motherfuckin' starboy",
    '(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)',
    "Look what you've done",
    '(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)',
    "I'm a motherfuckin' starboy",

    '[Verse 3]',
    'Let a nigga brag Pitt',
    'Legend of the fall, took the year like a bandit',
    'Bought Mama a crib and a brand new wagon',
    "Now she hit the grocery shop lookin' lavish",
    'Star Trek roof in that Wraith of Khan',
    'Girls get loose when they hear this song',
    'A hundred on the dash get me close to God',
    "We don't pray for love, we just pray for cars",

    '[Pre-Chorus]',
    'House so empty, need a centerpiece',
    'Twenty racks a table, cut from ebony',
    'Cut that ivory into skinny pieces',
    'Then she clean it with her face, man, I love my baby, ah',
    "You talkin' money, need a hearin' aid",
    "You talkin' 'bout me, I don't see the shade",
    'Switch up my style, I take any lane',
    'I switch up my cup, I kill any pain',

    '[Chorus]',
    '(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)',
    "Look what you've done",
    '(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)',
    "I'm a motherfuckin' starboy",
    '(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)',
    "Look what you've done",
    '(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)',
    "I'm a motherfuckin' starboy",
    '(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)',
    "Look what you've done",
    '(Ha-ha-ha-ha-ha, ha-ha-ha-ha-ha)',
    "I'm a motherfuckin' starboy",
  ],
  [
    '[Verse 1]',
    "She'd take the world off my shoulders",
    'If it was ever hard to move',
    "She'd turn the rain to a rainbow",
    'When I was living in the blue',
    "Why then, if she's so perfect",
    'Do I still wish that it was you?',
    "Perfect don't mean that it's workin'",
    'So what can I do? (Ooh)',

    '[Pre-Chorus]',
    "When you're out of sight",
    'In my mind',

    '[Chorus]',
    "'Cause sometimes, I look in her eyes",
    "And that's where I find a glimpse of us",
    'And I try to fall for her touch',
    "But I'm thinkin' of the way it was",
    "Said I'm fine and said I moved on",
    "I'm only here passing time in her arms",
    "Hopin' I'll find a glimpse of us",

    '[Verse 2]',
    'Tell me he savors your glory',
    'Does he laugh the way I did?',
    'Is this a part of your story?',
    'One that I had never lived',
    "Maybe one day, you'll feel lonely",
    "And in his eyes, you'll get a glimpse",
    "Maybe you'll start slippin' slowly and find me again",

    '[Pre-Chorus]',
    "When you're out of sight",
    'In my mind',

    '[Chorus]',
    "'Cause sometimes, I look in her eyes",
    "And that's where I find a glimpse of us",
    'And I try to fall for her touch',
    "But I'm thinkin' of the way it was",
    "Said I'm fine and said I moved on",
    "I'm only here passing time in her arms",
    "Hopin' I'll find a glimpse of us",

    '[Bridge]',
    'Ooh',
    'Ooh-ooh-ooh',
    'Ooh',
    'Ooh-ooh-ooh',

    '[Chorus]',
    "'Cause sometimes, I look in her eyes",
    "And that's where I find a glimpse of us",
    'And I try to fall for her touch',
    "But I'm thinkin' of the way it was",
    "Said I'm fine and said I moved on",
    "I'm only here passing time in her arms",
    "Hopin' I'll find a glimpse of us",
  ],
  [
    '[Intro]',
    'Woah, woah, ehh',

    '[Verse 1]',
    'I left my girl back home',
    "I don't love her no more",
    "And she'll never fucking know that",
    "These fucking eyes that I'm staring at",
    'Let me see that ass',
    'Look at all this cash',
    'And I emptied out my cards too',
    "Now I'm fucking leaning on that",

    '[Pre-Chorus]',
    'Bring your love, baby, I could bring my shame',
    'Bring the drugs, baby, I could bring my pain',
    'I got my heart right here',
    'I got my scars right here',
    'Bring the cups, baby, I could bring the drank',
    'Bring your body, baby, I could bring you fame',
    "And that's my motherfucking words too",
    'Just let me motherfucking love you',

    '[Chorus]',
    "Listen, ma, I'll give you all I got",
    'Get me off of this, I need confidence in myself (Yeah, yeah, yeah, ohh, yeah)',
    "Ohh, listen, ma, I'll give you all of me",
    'Give me all of it, I need all of it to myself (Woah, woah)',
    'So tell me you love me',
    '(Only for tonight, only for the night)',
    "Even though you don't love me (Ohh, ohh)",
    'Just tell me you love me',
    "(I'll give you what I need, I'll give you all of me)",
    "Even though you don't love me (Ohh, ohh) (yeah, yeah) (yeah, yeah)",

    '[Verse 2]',
    'Let me see you dance',
    'I love to watch you dance',
    'Take you down another level',
    'And get you dancing with the Devil',
    'Take a shot of this',
    "But I'm warning you",
    "I'm on that shit that you can't smell, baby",
    'So, put down your perfume',

    '[Pre-Chorus]',
    'Bring your love, baby, I could bring my shame',
    'Bring the drugs, baby, I could bring my pain',
    'Oh, I got my heart right here',
    'Oh, I got my scars right here',
    'Bring the cups, baby, I could bring the drank',
    'Bring your body, baby, I could bring you fame',
    "And that's my motherfucking words too, ayy",
    'So let me motherfucking love you',

    '[Chorus]',
    "Listen, ma, I'll give you all I got",
    'Get me off of this (off of this), I need confidence (confidence) in myself (Ooh, eh, ehh)',
    "Listen, ma, I'll give you all of me (Ooh)",
    'Give me all of it, I need all of it to myself (I need all of it)',
    'So tell me you love me, yeah',
    '(Only for tonight, only for the night)',
    "Even though you don't love me (Ohh, ohh)",
    'Just tell me you love me',
    "(I'll give you what I need, I'll give you all of me)",
    "Even though you don't love me (Ohh, ohh)",
    'Ohh',
  ],
  [
    '[Verse 1: SiR]',
    "I been goin' silly for the Westside (Westside)",
    "You might catch me rollin' where the reps ride (Real reps, real reps, real reps)",
    "Ain't no opposition, I'm the best, right? (Yeah, yeah)",
    'I might take my city on a test drive (Test drive)',
    "You don't wanna see me on a good day (Oh no, oh no)",
    "You don't wanna see me on a bad day (No, no, no, oh no)",
    'I was just a nigga with some hoop dreams (Hoop dreams)',
    "Now, I'm in the league, bitch",
    "Now, I'm in the lead, bitch",
    'I can slam dunk but I just layup (I just layup, ayy)',
    "Smokin' marijuana 'til I, ooh (Ooh), what? (What?) wake up",
    "May not understand me 'cause it's all real (I'm all real, all real)",
    "And I don't really give a damn how y'all feel (No, no)",

    '[Chorus: SiR]',
    "Baby, I'm just tryna let my hair down (My hair down)",
    "Baby, I'm just tryna let my hair down (My hair down)",
    "Everybody's watchin', I'm aware now (I'm aware now)",
    "But I can't find a reason I should care now (I should care now)",
    "Baby, I'm just tryna let my–",

    '[Post-Chorus: SiR]',
    'If I take off my cool, do you promise to stay?',
    'If I give you my heart, would you throw it away?',
    'Do you mean what you say when you tell me you love me?',
    'Do you really?',
    'Do you really?',

    '[Verse 2: Kendrick Lamar]',
    'Itty-bitty bitch is a numerologist',
    'Got your number where I live',
    "I'ma get you outta pocket like a quarterback blitz",
    "That's a everyday faucet, make it wet, make it rinse",
    "Skeletons in your closet but your past don't exist",
    'Got a pad on your list, got a pad on your lock',
    "Calabas' ain't the move, that's where everybody live",
    'Plus the mountain is hot, you forgot what you got, ah!',
    "Hol' up, nuisance (I say it, I say it, I say it)",
    "I recommend 'em all with acoustics (I say it, I say it, I say it)",
    'I recommend a bed for the juices (I say it, I say it, I say it)',
    'I recommend you live where the truth is (I say it, I say it, I say it)',
    'Psychedelic views and infinity pools, yeah, checking out',
    'Once I sweat them edges out',
    'Hair down like vanity',
    'I got the fuck-ups, I got the damage fees',
    'I got the gold dust, I got the anesthesia',
    "When you chose up, this ain't a fantasy",
    "We 'bout to go up, see underhanding me never got no love",
    "But understandin' me maybe can mold us and–",

    '[Chorus: SiR]',
    "Baby, I'm just tryna let my hair down (My hair down)",
    "Baby, I'm just tryna let my hair down (My hair down)",
    "Everybody's watching, I'm aware now (I'm aware now)",
    "But I can't find a reason I should care now (I should care now)",
    "Baby, I'm just tryna let my–",

    '[Post-Chorus: SiR]',
    'If I take off my cool, do you promise to stay?',
    'If I give you my heart, would you throw it away?',
    'Do you mean what you say when you tell me you love me?',
    'Do you really?',
    'Do you really?',
  ],
  [
    '[Intro]',
    "I'm fucking gone right now",
    "I'm fucking gone right now",
    '"Listen, listen"',

    '[Verse 1]',
    'From the morning to the evening',
    'Complaints from the tenants',
    'Got the walls kicking like they six months pregnant',
    'Drinking Alizé with our cereal for breakfast',
    'Girls calling cabs at dawn quarter to seven',
    "Sky's getting cold, we're flying from the north",
    "Rockin' with our city like a sold out show",
    "House full of pros that specialize in the ho'in'",
    'Make that money rain as they taking off they clothes',
    'Order plane tickets',
    'Cali is the mission',
    "Visit every month like I'm split life living",
    'Let the world listen',
    "If a hater's caught slipping",
    'Then my niggas stay tight',
    'Got my back like Pippen',
    'Fast life gripping',
    "Yeah, we still tippin'",
    'Codeine cups paint a picture so vivid',
    'Fakes try to mimic',
    'Get girls timid',
    'But behind closed doors they get poles so rigid',

    '[Chorus]',
    'All that money, the money is the motive',
    'All that money, the money is the motive',
    'All that money, the money she be folding',
    'Girl, put in work, girl, girl, put in work',
    'Girl, put in work, girl, girl, put in work',
    'Girl, put in work',

    '[Verse 2]',
    'Push it to the limit',
    'Push it through the pain',
    'I push it for the pleasure like a virgin to the game',
    'A virgin to that money',
    'A virgin to the fame',
    'So this my only chance',
    "And when I'm over only pray",
    'That I flow from the bottom',
    'Closer to the top',
    'The higher that I climb',
    "The harder I'ma drop",
    'These pussy ass niggas tryna hold on to their credit',
    'So I tell them use a debit',
    'Watch they image start to lessen',
    'I warn them like discretion',
    'Why these niggas testing?',
    'Always fucking testing',
    'Why these niggas testing?',
    'Shit that I got them on straight bar hopping',
    'To the music of the ambiance',
    'Get shit popping',
    'Zombies of the night (Zombies of the night)',
    "Niggas ain't talking if they hyping to the crew",
    'Get it in like pockets',
    'Downtown loving',
    'When the moon coming',
    'Only place to find bassheads and hot women',

    '[Chorus]',
    'All that money, the money is the motive',
    'All that money, the money is the motive',
    'All that money, the money she be folding',
    'Girl, put in work, girl, girl, put in work',
    'Girl, put in work, girl, girl, put in work',
    'Girl, put in work',

    '[Verse 3]',
    'Better slow down',
    "She'll feel it in the morning",
    "Ain't the kind of girl you'll be seeing in the morning",
    "Too damn raw, ain't no nigga with her rollin'",
    "Ain't no nigga that she holding",
    'Man, her love is too damn foreign',
    'Look at all that money',
    'The money is the motive (The money is the motive)',
    'All that money',
    'The money she be folding (The money she be folding)',
    'Girl, put in work, girl, girl, put in work',
    'Girl, put in work, girl, girl, put in work',

    '[Chorus]',
    'All that money, the money is the motive',
    'All that money, the money is the motive',
    'All that money, the money she be folding',
    'Girl, put in work, girl, girl, put in work',
    'Girl, put in work, girl, girl, put in work',
    'Girl, put in work',
  ],
  [
    '[Verse 1]',
    "I'm scared (Oh-oh-oh)",
    "It feels like you don't care (Ooh-ooh)",
    'Enlighten me, my dear (Ooh-ooh-ooh)',
    'Why am I still here? Mm (Oh-oh)',
    "I don't mean to be",
    'Complacent with the decisions you made',
    'But why? Mm',

    '[Verse 2]',
    'In the back of my mind',
    'You died',
    "And I didn't even cry",
    'No, not a single tear',
    "And I'm sick of waiting patiently",
    "For someone that won't even arrive",

    '[Bridge]',
    'Ooh-ooh-ooh-ooh-ooh-oh',

    '[Verse 3]',
    'In the back of my mind',
    'I killed you',
    "And I didn't even regret it",
    "I can't believe I said it",
    "But it's true",
    'I hate you',
  ],
  [
    '[Intro]',
    'Bangladesh',
    'Young Money!',
    'You dig?',
    "Mack, I'm going in",

    '[Verse 1]',
    "A millionaire, I'm a Young Money millionaire",
    'Tougher than Nigerian hair',
    "My criteria compared to your career just isn't fair",
    "I'm a venereal disease, like a menstrual bleed",
    'Through the pencil, and leak on the sheet of the tablet in my mind',
    "'Cause I don't write shit, 'cause I ain't got time",
    "'Cause my seconds, minutes, hours go to the almighty dollar",
    'And the almighty power of that ch-cha-cha-cha-chopper',
    'Sister, brother, son, daughter, father; mother-fuck a copper',
    "Got the Maserati dancin' on the bridge, pussy poppin'",
    "Tell the coppers, 'Ha-ha-ha-ha, You can't catch him, you can't stop him'",
    "I go by them goon rules: if you can't beat 'em, then you pop 'em",
    "You can't man 'em, then you mop 'em",
    "You can't stand 'em, then you drop 'em",
    "You pop 'em 'cause we pop 'em like Orville Redenbacher",

    '[Chorus]',
    "Motherfucker, I'm ill",

    '[Verse 2]',
    'A million here, a million there',
    'Sicilian bitch with long hair, with coke in her derrière',
    'Like smoking the thinnest air',
    "I open the Lamborghini, hopin' them crackers see me",
    "Like, 'Look at that bastard Weezy!'",
    "He's a beast, he's a dog, he's a mothafuckin' problem",
    "Okay, you're a goon, but what's a goon to a goblin?",
    "Nothin', nothin', you ain't scarin' nothin'",
    "On some faggot bullshit: call 'em Dennis Rodman",
    'Call me what you want, bitch! Call me on my Sidekick!',
    "Never answer when it's private, damn, I hate a shy bitch",
    "Don't you hate a shy bitch? Yeah, I ate a shy bitch",
    "She ain't shy no more, she changed her name to My Bitch, haha",
    "Yeah, nigga, that's my bitch, so when she ask",
    "For the money when you through, don't be surprised, bitch!",
    "And it ain't trickin' if you got it",
    "But you like a bitch with no ass: You ain't got shit",
    "Motherfucker, I'm ill, not sick",
    "And I'm okay, but my watch sick, yeah, my drop sick",
    "Yeah, my Glock sick, and my knot thick — I'm it",

    '[Verse 3]',
    "See, they say I'm rappin' like B.I.G., Jay, and 2Pac",
    'André 3000, where is Erykah Badu at? Who that?',
    "Who that said they gon' beat Lil Wayne?",
    "My name ain't Bic, but I keep that flame, man",
    'Who that one that do that, boy?',
    'You knew that true that, swallow',
    'And I be the shit, now you got loose bowels',
    "I don't owe you like two vowels",
    'But I would like for you to pay me by the hour, haha',
    "And I'd rather be pushin' flowers",
    "Than to be in the pen sharin' showers",
    'Tony told us this world was ours',
    'And the Bible told us every girl was sour',
    "Don't play in her garden and don't smell her flower",
    'Call me Mr. Carter or Mr. Lawn Mower',
    "Boy, I got so many bitches, like I'm Mike Lowrey",
    "Even Gwen Stefani said she couldn't doubt me",
    "Motherfucker, I say 'Life ain't shit without me'",
    "Chrome lips pokin' out the coupe, look like it's poutin'",
    'I do what I do, and you do what you can do about it',
    'Bitch, I can turn a crack rock into a mountain — dare me',
    "Don't you compare me, 'cause there ain't nobody near me",
    "They don't see me but they hear me",
    "They don't feel me but they fear me",
    "I'm illy, C3, 3 Peat",
  ],
  [
    '[Chorus]',
    "One spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",

    '[Verse 1]',
    "Tell me who that nigga if it ain't me",
    "If it ain't a party, then it's finna be",
    "Never had a problem that I couldn't solve",
    'It must be official if I get involved',
    "Quarter pound of fire burnin' daily",
    "Harder to remember, gettin' harder to remember",
    "I've been through enough to drive me crazy",
    "I don't think my mama's gonna save me",

    '[Refrain]',
    "Maybe I'm not flyin', but I'm floatin'",
    "If we're not headed to the top, where we goin'?",
    "Two miles-an-hour, can you picture me rollin'?",
    "'Cause life is so much better when you live in slow motion",

    '[Chorus]',
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",
    '(Slow motion)',
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",

    '[Verse 2]',
    'Pardon me while I elevate',
    "May not be on time, but I'm never late",
    "Blazin' like the player that you wanna be",
    'Flavor like your baby mama cup of tea',
    "You see the company I'm keepin' now",
    "Feelin' like I'm dreamin', I keep feelin' like I'm dreamin'",
    "Don't come around if you don't be around",
    'I been the man you believe me now',

    '[Refrain]',
    "Maybe I'm not flyin', but I'm floatin'",
    "If we're not headed to the top, where we goin'?",
    "Two miles an hour, can you picture me rollin'?",
    "'Cause life is so much better when you live in slow motion",

    '[Chorus]',
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",
    '(Slow motion)',
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",
    "Ca one spliff a day'll keep the evil away",
  ],
  [
    '[Verse 1: Frank Ocean]',
    'Bad luck to talk on these rides',
    'Mind on the road, your dilated eyes watch the clouds float',
    'White Ferrari, had a good time',
    "Sweet sixteen, how was I supposed to know anything? (Love)",
    'I let you out at Central',
    "I didn't care to state the plain",
    'Kept my mouth closed',
    "We're both so familiar",
    'White Ferrari, good times',

    '[Verse 2: Frank Ocean]',
    'Stick by me, close by me',
    'You were fine, you were fine here',
    "That's just a slow body",
    'You left when I forgot to speak',
    'So I text the speech, lesser speeds, Texas speed, yes',
    'Basic takes its toll on me',
    "'ventually, 'ventually, yes",
    "Ah, on me 'ventually, 'ventually, yes",
    'I care for you still, and I will forever',
    'That was my part of the deal, honest',
    'We got so familiar',
    'Spending each day of the year',
    'White Ferrari, good times',

    '[Bridge: Frank Ocean & Kanye West]',
    'In this life (Life), in this life (Life)',
    'One too many years',
    'Some tattooed eyelids on a facelift',
    'Thought you might want to know now',
    'Mind over matter is magic, I do magic',
    "If you think about it, it'll be over in no time",
    "And that's life (Love)",
    'Love (Love)',

    '[Verse 3: Frank Ocean]',
    "I'm sure we're taller in another dimension",
    "You say we're small and not worth the mention",
    "You're tired of movin' (Woo), your body's achin' (Woah)",
    "We could vacay, there's places to go",
    "Clearly, this isn't (The way) all that there is",
    "Can't take what's been given (No way)",
    "But we're so okay here (We're fine), we're doing fine (We're fine)",
    'Primal and naked',
    'You dream of walls that hold us in prison (Love)',
    "It's just a skull, least that's what they call it",
    "And we're free to roam",
  ],
];

// Example of how to use the array
console.log(lyrics[0]);
